'use strict';

const path = require('path');
const fs = require('fs');
const dotenv = require('dotenv');

function forceLoadEnv(envPath) {
  try {
    if (fs.existsSync(envPath)) {
      const envConfig = dotenv.parse(fs.readFileSync(envPath));
      for (const k in envConfig) {
        process.env[k] = envConfig[k];
      }
    }
  } catch (e) {
    console.error('Error force loading env:', e.message);
  }
}

class QuotaExceededError extends Error {
  constructor(message) {
    super(message);
    this.name = 'QuotaExceededError';
    this.status = 503;
  }
}

class LLMService {
  constructor(catalystApp) {
    this.app = catalystApp;

    // Load environment variables from the parent directories
    const functionsRootEnv = path.resolve(__dirname, '..', '..', '..', '.env');
    forceLoadEnv(functionsRootEnv);

    const functionRootEnv = path.resolve(__dirname, '..', '..', '.env');
    forceLoadEnv(functionRootEnv);

    this.endpointUrl = process.env.QUICKML_ENDPOINT_URL;
    if (!this.endpointUrl) {
      throw new Error('Configuration Error: QUICKML_ENDPOINT_URL is not defined in environment variables.');
    }
    this.orgId = process.env.QUICKML_ORG_ID || process.env.X_ZOHO_CATALYST_ORG_ID;
    if (!this.orgId) {
      throw new Error('Configuration Error: QUICKML_ORG_ID is not defined in environment variables.');
    }
  }

  /**
   * Generates content and parses the response as JSON.
   * 
   * @param {string} prompt - Prompt instruction
   * @returns {Promise<object>} Parsed JSON response
   */
  async generateJSON(prompt) {
    const text = await this.generateText(prompt);
    try {
      let cleaned = text.trim();
      
      // 1. Strip thinking tags if present
      if (cleaned.includes('</think>')) {
        cleaned = cleaned.split('</think>').pop().trim();
      }

      // 2. Try to locate target JSON block using known key anchors
      let startPos = -1;
      const intentPos = cleaned.lastIndexOf('"intent"');
      const responsePos = cleaned.lastIndexOf('"response"');
      const keyPos = Math.max(intentPos, responsePos);
      
      if (keyPos !== -1) {
        startPos = cleaned.lastIndexOf('{', keyPos);
      }
      
      if (startPos !== -1) {
        const lastBrace = cleaned.lastIndexOf('}');
        if (lastBrace > startPos) {
          cleaned = cleaned.substring(startPos, lastBrace + 1);
        }
      } else {
        // Fallback: Locate first '{' and last '}'
        const firstBrace = cleaned.indexOf('{');
        const lastBrace = cleaned.lastIndexOf('}');
        if (firstBrace !== -1 && lastBrace !== -1 && lastBrace > firstBrace) {
          cleaned = cleaned.substring(firstBrace, lastBrace + 1);
        } else {
          // Fallback: Code block parsing
          if (cleaned.includes('```json')) {
            cleaned = cleaned.split('```json')[1].split('```')[0];
          } else if (cleaned.includes('```')) {
            cleaned = cleaned.split('```')[1].split('```')[0];
          }
        }
      }
      
      return JSON.parse(cleaned.trim());
    } catch (e) {
      console.error('[LLMService] Failed to parse JSON response. Raw output:', text, e.message);
      throw new Error('Invalid JSON response generated by the model.');
    }
  }

  /**
   * Generates standard text content.
   * 
   * @param {string} prompt - Prompt instruction
   * @returns {Promise<string>} Text response
   */
  async generateText(prompt) {
    try {
      // 1. Resolve OAuth token from SDK dynamically
      const tokenObj = await this.app.credential.getToken();
      const token = tokenObj.access_token;
      if (!token) {
        throw new Error('OAuth Token Error: Failed to retrieve access token from Catalyst SDK credential helper.');
      }

      // 2. Perform direct HTTP POST to QuickML chat completions endpoint
      const headers = {
        'Content-Type': 'application/json',
        'CATALYST-ORG': this.orgId,
        'Authorization': `Zoho-oauthtoken ${token}`
      };

      // Payload body strictly formatted according to Zoho Catalyst QuickML JSON schema
      const payload = {
        model: 'crm-di-glm47b_30b_it',
        messages: [
          {
            role: 'system',
            content: 'You are a helpful assistant.'
          },
          {
            role: 'user',
            content: prompt
          }
        ],
        temperature: 0.7,
        max_tokens: 2048,
        stream: false
      };

      console.log(`[LLMService] Making request to QuickML Endpoint URL: ${this.endpointUrl}`);
      const response = await fetch(this.endpointUrl, {
        method: 'POST',
        headers,
        body: JSON.stringify(payload)
      });

      const responseBody = await response.json();
      console.log(`[LLMService Debug] QuickML response status: ${response.status}`);

      if (!response.ok) {
        const errorMsg = responseBody.error || responseBody.message || JSON.stringify(responseBody) || `HTTP ${response.status}`;
        throw new Error(`QuickML endpoint returned error: ${errorMsg}`);
      }

      // Robust fallback extraction of the response text content
      let text = '';
      if (responseBody.choices && responseBody.choices[0] && responseBody.choices[0].message) {
        text = responseBody.choices[0].message.content;
      } else if (responseBody.choices && responseBody.choices[0] && responseBody.choices[0].text) {
        text = responseBody.choices[0].text;
      } else if (responseBody.result && Array.isArray(responseBody.result)) {
        text = responseBody.result[0];
      } else if (responseBody.result) {
        text = responseBody.result;
      } else if (responseBody.response) {
        text = responseBody.response;
      } else if (responseBody.output) {
        text = responseBody.output;
      } else {
        throw new Error('Received empty or invalid response format from QuickML LLM serving.');
      }

      let cleanedText = text.trim();
      // Strip thinking tags if present
      if (cleanedText.includes('</think>')) {
        cleanedText = cleanedText.split('</think>').pop().trim();
      }

      return cleanedText;
    } catch (error) {
      console.error('[LLMService] Error during QuickML predict:', error.message || error);
      const msg = (error.message || '').toLowerCase();
      if (msg.includes('quota') || msg.includes('rate limit') || msg.includes('limit exceeded') || error.status === 429 || error.status === 503) {
        throw new QuotaExceededError('QuickML quota exceeded. Please retry after the suggested delay.');
      }
      throw error;
    }
  }
}

module.exports = {
  LLMService,
  QuotaExceededError
};
